### ISSUE TITLE
Add automated typos checks in the pull requests tests

### ISSUE THREAD

**Issue by amousset** [darktable-org/dtdocs#379]
Some tools like https://github.com/crate-ci/typos are designed to only detect a list of known typos and thus have a very low rate of false positives, so they could be used to automatically detect typos in pull requests before merging them in the docs.

A currently working config (as `.typos.toml`):

```toml
files.extend-exclude = ["po/", "*.svg"]

[default.extend-words]
# HaldCLUT
hald = "hald"

# used in a page id
mutiple = "mutiple"
```
